
title: panmari's blog
description: >- # this means to ignore newlines until "baseurl:"
  Learn something new every day
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://panmari.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  panmari

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

